Elsasstv/Elsasstv/urls.py
from django.contrib import admin
from django.urls import path, include


import Elsasstv.views as views

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('', include('django.contrib.auth.urls')),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('search/', include('search.urls')),
        
]

Elsasstv/accounts/urls.py
from django.contrib import admin
from django.urls import path


import accounts.views as views


app_name = 'accounts'

urlpatterns = [

    path('profile', views.profile, name='profile'),
    path('settings', views.settings, name='settings'),
    path('list_users', views.list_users, name='list_users'),
    path('<int:friend_id>/friend_request', views.friend_request, name='friend_request'),
    path('<int:friendship_id>/<int:status>/accept_or_refuse', views.accept_or_refuse, name='accept_or_refuse'),
    path('<int:friend_id>/delete_friend', views.delete_friend, name='delete_friend'),
    path('<int:friend_id>/friend_infos', views.friend_infos, name='friend_infos'),
    

]

Elsasstv/movies/urls.py
from django.contrib import admin
from django.urls import path

import movies.views as views


app_name = 'movies'

urlpatterns = [

    path('', views.home, name='home'),
	path('<int:movie_id>/detail', views.detail, name="detail"),
    path('<int:person_id>/person-detail', views.person, name="person"),
    path('<int:movie_id>/create_favorite', views.create_favorite, name='create_favorite'),
    path('<int:movie_id>/remove_favorite', views.remove_favorite, name='remove_favorite'),
    
]

Elsasstv/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class UserCustom(models.Model):  
    """As the User model is not changeable, this model, connected to User by a one to one relationship
    allows to create custom user objects, that can be connected to themselves through the Friendship table
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    friends = models.ManyToManyField("self", 
                through="Friendship",
                through_fields=("source_user","target_user"),
                symmetrical=False)
  

class Friendship(models.Model): 
    """Connects custom users through a many to many relationship. The status of the friendship
    describes if this is a not-yet-accepted request (status = 0), an accepted request (status = 1),
    or a refused request/deleted friend (status = 2)
    """
    source_user = models.ForeignKey(UserCustom, on_delete=models.CASCADE)
    target_user = models.ForeignKey(UserCustom, on_delete=models.CASCADE, related_name='target_user')
    status = models.IntegerField(null=True)
        

Elsasstv/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist

from accounts.get_friends import get_notif, get_friends
from accounts.models import UserCustom, Friendship
from search.documents import UserDocument
from movies.models import Movie, Person


@login_required
def profile(request):
    """View rendering the detailed informations of a user"""
    current_user = request.user
	# getting the popular_movies
    popular_movies = Movie.objects.order_by('-popularity')[:100]
    # Getting the favorite movies
    favorite_movies = current_user.movie_set.all()
    # Getting the friends
    friends = get_friends(current_user)
    nb_friends = len(friends)
    friend_ids = [friend.id for friend in friends]
    other_users = User.objects.exclude(Q(id=request.user.id) | Q(id=1)) 
    # Getting the requests for the notifications
    friend_requests = get_notif(request.user) 
    nb_requests = len(friend_requests)
    # Search bar for username
    u = request.GET.get('u')
    if u:
        search = UserDocument.search().query("match", username=u)[:100]
    else:
        search = ''
    return render(request, 'accounts/profile.html', locals())

@login_required
def list_users(request):
    """Displays a list of all the current users, with the exception of the Elsasstv superuser, and the current user"""
    friends = get_friends(request.user)
    friend_ids = [friend.id for friend in friends]
    other_users = User.objects.exclude(Q(id=request.user.id) | Q(id=1)) 
    # Getting the requests for the notifications
    friend_requests = get_notif(request.user) 
    nb_requests = len(friend_requests)
    return render(request, 'accounts/list_users.html', locals())

@login_required
def friend_request(request, friend_id):
    """Sending a friend request to a user, and creating a new relationship"""
    current_user = request.user.usercustom
    target_user = User.objects.get(id=friend_id).usercustom
    new_friendship, created = Friendship.objects.get_or_create(source_user=current_user, target_user=target_user, status=0)
    if created:
        new_friendship.save()  
    return redirect('accounts:profile')

@login_required
def accept_or_refuse(request, friendship_id, status):
    """Changing the status of the friendship between user. If the selected status is 1, the users are now friends,
    if its 2, the friendship is rejected
    """
    friendship = Friendship.objects.get(id=friendship_id)
    # Accepted
    if status == 1:
        friendship.status = 1
        friendship.save()
    # Refused
    else:
        friendship.status = 2
        friendship.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER')) # Staying on the same page

@login_required
def delete_friend(request, friend_id):
    """Deletes a friend by looking for the corresponding relationship(s) and setting its status to 2"""
    friend = User.objects.get(id=friend_id)
    current_user = request.user 
    # Friendship where the current_user is the target   
    try:
        friendship1 = Friendship.objects.get(source_user=friend.usercustom, target_user=current_user.usercustom, status=1)
        if friendship1:
            friendship1.status = 2
            friendship1.save()
    except ObjectDoesNotExist:
        pass
    # Friendship where the current_user is the source
    try:
        friendship2 = Friendship.objects.get(source_user=current_user.usercustom, target_user=friend.usercustom, status=1)    
        if friendship2:
            friendship2.status = 2
            friendship2.save()
    except ObjectDoesNotExist:
        pass
    return HttpResponseRedirect(request.META.get('HTTP_REFERER')) # Staying on the same page
    
@login_required
def friend_infos(request, friend_id):
    """Displays all the informations of a friend"""
    friend = User.objects.get(id=friend_id)
    favorite_movies = friend.movie_set.all()
    # getting the popular_movies
    popular_movies = Movie.objects.order_by('-popularity')[:100]
    # Getting the requests for the notifications
    friend_requests = get_notif(request.user) 
    nb_requests = len(friend_requests)
    return render(request, 'accounts/friend_infos.html', locals())     

@login_required
def settings(request):
    """Displays all informations of the current user + modifications forms"""
    # Getting the requests for the notifications
    friend_requests = get_notif(request.user) 
    nb_requests = len(friend_requests)
    return render(request, 'accounts/settings.html', locals())

Elsasstv/accounts/templates/accounts/friend_infos.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>

<html lang="en">

    <head>
        
        {% block css %}{% endblock %} 

        {% block head %}
        <title>Elasstv - movie</title>
        {% endblock %}

    </head>


    <body id="page-top">

		{% block body %}
		
		{% include 'header-movie.html' %}

        <div id="sidebar-bg">
					<div id="content-sidebar-pro">
			
						<div id="content-sidebar-info">
							<img src="{% static 'accounts/images/profile-image-sidebar.jpg' %}" alt="profile-image">
							<div id="profile-sidebar-name">
								<h6>Username :</h6>
								<h5>{{friend.username}}</h5>
							</div>
							<div id="profile-sidebar-gradient"></div>
						</div>
						
						<div class="content-sidebar-section">
							<h3 class="content-sidebar-sub-header">Informations</h3>
							<ul id="friends-activity-feed friends-activity-feed2">

									<li>First name: {{ friend.first_name }}</li>
									<li>Last name: {{ friend.last_name }}</li>
 									<li>email: {{ friend.email }}</li>
								
								</ul>
							
							<div class="clearfix"></div>
							</div>
						
							<div class="content-sidebar-section">
									<h3 class="content-sidebar-sub-header">Activity</h3>
									<ul id="friends-activity-feed">
										<li>Last time logged: {{ friend.last_login }}</li>
										<li>Joined since the: {{ friend.date_joined }}</li>
									<div class="clearfix"></div>
								</div>

						
						
					</div>
				
					<main id="col-main-with-sidebar">
							<div class="dashboard-container">
									<!-- Nav tabs -->

									<ul class="dashboard-sub-menu nav nav-tabs" role="tablist">
									  <li class="nav-item">
										<a class="nav-link active" data-toggle="tab" href="#favorites">Favorites</a>
									  </li>
									  <li class="nav-item">
										<a class="nav-link" data-toggle="tab" href="#watchlist">Watchlist</a>
									  </li>
									</ul>
								  
									<!-- Tab panes -->
									<div class="tab-content">
									  <div id="favorites" class="container tab-pane active"><br>

										<div class="row">
												{% for mov in favorite_movies%}
                									<div class="col-12 col-md-6 col-lg-4 col-xl-3">
                									    <div class="item-listing-container-skrn">
                									        <a href="/movies/{{mov.id}}/detail"><img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2/{{mov.poster_path}}" alt="Listing"></a>
                									        <div class="item-listing-text-skrn">
                									            <div class="item-listing-text-skrn-vertical-align"><h6><a href="/movies/{{mov.id}}/detail">{{mov.title}}</a></h6>
                									              <div
                									                class="circle-rating-pro"
                									                data-value="0.86"
                									                data-animation-start-value="0.86"
                									                data-size="32"
                									                data-thickness="3"
                									                data-fill="{
                									                  &quot;color&quot;: &quot;#2325c2  &quot;
                									                }"
                									                data-empty-fill="#def6de"
                									                data-reverse="true"
                									              ><span style="color:#2325c2  ;">{{mov.vote_average}}</span></div>
                									            </div>  
                									        </div>  
                									    </div>  
                									</div>  
												{% endfor %} 
												
											</div>

									  </div>

									  <div id="watchlist" class="container tab-pane fade"><br>


										<div class="row">
												{% for mov in popular_movies%}
                									<div class="col-12 col-md-6 col-lg-4 col-xl-3">
                									    <div class="item-listing-container-skrn">
                									        <a href="/movies/{{mov.id}}/detail"><img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2/{{mov.poster_path}}" alt="Listing"></a>
                									        <div class="item-listing-text-skrn">
                									            <div class="item-listing-text-skrn-vertical-align"><h6><a href="/movies/{{mov.id}}/detail">{{mov.title}}</a></h6>
                									              <div
                									                class="circle-rating-pro"
                									                data-value="0.86"
                									                data-animation-start-value="0.86"
                									                data-size="32"
                									                data-thickness="3"
                									                data-fill="{
                									                  &quot;color&quot;: &quot;#2325c2  &quot;
                									                }"
                									                data-empty-fill="#def6de"
                									                data-reverse="true"
                									              ><span style="color:#2325c2  ;">{{mov.vote_average}}</span></div>
                									            </div>  
                									        </div>  
                									    </div>  
                									</div>  
												{% endfor %} 
												
											</div>

									  </div>
									</div>
							
						</div>
					
			
			
				</main>
			
					
				</div>  
    	{% endblock %}

        {% block pre-footer %}
    
    	{% endblock %}

        {% include 'footer.html' %}

    </body>


</html>

Elsasstv/accounts/templates/accounts/list_users.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>

<html lang="en">

    <head>
        
        {% block css %}{% endblock %} 

        {% block head %}
        <title>Elasstv - movie</title>
        {% endblock %}

    </head>


    <body id="page-top">

		{% block body %}
		
		{% include 'header-movie.html' %}

        <div id="sidebar-bg">
				  
				  <main id="col-main">
					  
					  <div class="dashboard-container">
						  
						  <ul class="dashboard-sub-menu">
							  <li class="current"><a href="dashboard-account.html">List of other users</a></li>
						  </ul><!-- close .dashboard-sub-menu -->
						  
						  <div class="container-fluid">
							  <div class="row">
							  
								  
									  <form class="account-settings-form">
								  
									  <h5>List of users</h5>
										<ul>
										{% for other in other_users %}
											{% if other.id in friend_ids %}
												<li> {{other.username}} <p>Already a friend</p> </li>
											{% else %}								
												<li> {{other.username}} <p><a href="{% url 'accounts:friend_request' other.id%}" class="btn btn-green-pro">Send a friend request</a></p> </li>
											{% endif %}									
										{% endfor %}
										</ul>

									
				
							  
							  </div><!-- close .row -->
						  </div><!-- close .container-fluid -->
								  
					  </div><!-- close .dashboard-container -->
				  </main>
				  
				  
				  </div><!-- close #sidebar-bg-->
				  
    	{% endblock %}

        {% block pre-footer %}
    
    	{% endblock %}

        {% include 'footer.html' %}

    </body>


</html>

Elsasstv/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>

<html lang="en">

    <head>
        
        {% block css %}{% endblock %} 

        {% block head %}
        <title>Elasstv - movie</title>
        {% endblock %}

    </head>


    <body id="page-top">

		{% block body %}
		
		{% include 'header-movie.html' %}

        <div id="sidebar-bg">
					<div id="content-sidebar-pro">
			
						<div id="content-sidebar-info">
							<img src="{% static 'accounts/images/profile-image-sidebar.jpg' %}" alt="profile-image">
							<div id="profile-sidebar-name">
								<h6>Logged as :</h6>
								<h5>{{user.username}}</h5>
							</div>
							<div id="profile-sidebar-gradient"></div>
							<a href="/accounts/settings" class="edit-profile-sidebar"><i class="fas fa-pencil-alt"></i></a>
						</div>
						
						<div class="content-sidebar-section">
							<h3 class="content-sidebar-sub-header">Friend{{ nb_friends|pluralize }}: {{ nb_friends }}</h3>
							<ul id="friends-activity-profiles">

									{% for friend in friends%}
											<li><a href="{% url 'accounts:friend_infos' friend.id %}">
												<figure>
													<img src="{% static 'images/user-profile-2.jpg' %}" alt="{{ friend.username }}"><figcaption> {{ friend.username }} </figcaption> </figure> </a></li>
									{% endfor %}	
								
								</ul>
							
							<div class="lookup-friend-side"> <a data-toggle="tab" href="#friends" class="btn btn-green-pro">Look for a friend!</a>
							</div>
							<div class="clearfix"></div>
							</div>
						
						<div class="content-sidebar-section">
							<h3 class="content-sidebar-sub-header">Friends Notifications</h3>
							<ul id="friends-activity-feed">
									{% for friendship in friend_requests %}
									<li>
											
											<a>
											<img src="{% static 'images/user-profile-2.jpg' %}" alt="Profile">
											<strong>{{ friendship.source_user.user.username }}</strong> wants to be your friend  </a>

											<div class="notify-button-side row">
													<div class="notif col-xs-6">
													<a href="{% url 'accounts:accept_or_refuse' friendship.id 1 %}" class="btn btn-accept button-notif">Accept</a> </div>
													<div class="notif col-xs-6">
													 <a href="{% url 'accounts:accept_or_refuse' friendship.id 2 %}" class="btn btn-refuse button-notif">Refuse</a></div>
													</div>
									</li>
									{% endfor %}</ul></ul>
							<div class="clearfix"></div>
						</div>
						
						
					</div>
				
					<main id="col-main-with-sidebar">
							<div class="dashboard-container">
									<!-- Nav tabs -->
									
									<ul class="dashboard-sub-menu nav nav-tabs" role="tablist">
									  <li class="nav-item">
										{% if u is None %}
										<a class="nav-link active" data-toggle="tab" href="#favorites">Favorites</a>
										{% else %}
										<a class="nav-link" data-toggle="tab" href="#favorites">Favorites</a>
										{% endif%}
									  </li>
									  <li class="nav-item">
										<a class="nav-link" data-toggle="tab" href="#watchlist">Watchlist</a>
									  </li>
									  <li class="nav-item">
										{% if u is None %}
										<a class="nav-link" data-toggle="tab" href="#friends">Friends</a>
										{% else %}
										<a class="nav-link active" data-toggle="tab" href="#friends">Friends</a>
										{% endif%}
										</li>
									</ul>
									

									<!-- Tab panes -->
									<div class="tab-content">
											{% if u is None %}
										<div id="favorites" class="container tab-pane active"><br>
											{% else %}
											<div id="favorites" class="container tab-pane fade"><br>
											{% endif%}

										<div class="row">
												{% for mov in favorite_movies%}
                									<div class="col-12 col-md-6 col-lg-4 col-xl-3">
                									    <div class="item-listing-container-skrn">
                									        <a href="/movies/{{mov.id}}/detail"><img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2/{{mov.poster_path}}" alt="Listing"></a>
                									        <div class="item-listing-text-skrn">
                									            <div class="item-listing-text-skrn-vertical-align"><h6><a href="/movies/{{mov.id}}/detail">{{mov.title}}</a></h6>
                									              <div
                									                class="circle-rating-pro"
                									                data-value="0.86"
                									                data-animation-start-value="0.86"
                									                data-size="32"
                									                data-thickness="3"
                									                data-fill="{
                									                  &quot;color&quot;: &quot;#2325c2  &quot;
                									                }"
                									                data-empty-fill="#def6de"
                									                data-reverse="true"
                									              ><span style="color:#2325c2  ;">{{mov.vote_average}}</span></div>
                									            </div>  
                									        </div>  
                									    </div>  
                									</div>  
												{% endfor %} 
												
											</div>

									  </div>

									  <div id="watchlist" class="container tab-pane fade"><br>


										<div class="row">
												{% for mov in popular_movies%}
                									<div class="col-12 col-md-6 col-lg-4 col-xl-3">
                									    <div class="item-listing-container-skrn">
                									        <a href="/movies/{{mov.id}}/detail"><img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2/{{mov.poster_path}}" alt="Listing"></a>
                									        <div class="item-listing-text-skrn">
                									            <div class="item-listing-text-skrn-vertical-align"><h6><a href="/movies/{{mov.id}}/detail">{{mov.title}}</a></h6>
                									              <div
                									                class="circle-rating-pro"
                									                data-value="0.86"
                									                data-animation-start-value="0.86"
                									                data-size="32"
                									                data-thickness="3"
                									                data-fill="{
                									                  &quot;color&quot;: &quot;#2325c2  &quot;
                									                }"
                									                data-empty-fill="#def6de"
                									                data-reverse="true"
                									              ><span style="color:#2325c2  ;">{{mov.vote_average}}</span></div>
                									            </div>  
                									        </div>  
                									    </div>  
                									</div>  
												{% endfor %} 
												
											</div>

										</div>
										{% if u is None %}
										<div id="friends" class="container tab-pane fade">
												{% else %}
												<div id="friends" class="container tab-pane active">
														{% endif%}
											
											<br>
											<div class="row row-eq-height">

												<div class="col-sm-3 col-md-6 friend-list-col">

													
														<h5>List of friends :</h5>

								  
																<ul style="list-style: none;">
																{% for other in other_users %}
																	{% if other.id in friend_ids %}
																		<li> <a href="{% url 'accounts:friend_infos' other.id %}" class="a-friend">{{other.username}}</a> 
																			<a href="{% url 'accounts:delete_friend' other.id %}" class="btn btn-delete">Delete this friend</a>
																			</li>
																	{% else %}								
																		<li> <a href="{% url 'accounts:friend_infos' other.id %}" class="a-friend">{{other.username}}</a>
																		<a href="{% url 'accounts:friend_request' other.id%}" class="btn btn-send">Send a friend request</a>
																		</li>
																	{% endif %}									
																{% endfor %}
																</ul>
						
											</div>

											<div class="col-sm-3 col-md-6">
												
													<h5>Find a friend :</h5>
													<form method="get">
														<input id='u'  name='u' type="text" placeholder="Enter the username" aria-label="Search">
														</form>
														<br>
														{% if u is None %}
														{% else %}
														<h5>Search result:</h5>
														{% endif%}

														{% for user in search%}
														<a href="{% url 'accounts:friend_infos' user.id %}" class="a-friend">{{ user.username }}</a>
														{% endfor %}

												</div>


										</div>
										
									</div>
							
						</div>
					
			
			
				</main>
			
					
				</div>  
    	{% endblock %}

        {% block pre-footer %}
    
    	{% endblock %}

        {% include 'footer.html' %}

    </body>


</html>

Elsasstv/accounts/templates/accounts/settings.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>

<html lang="en">

    <head>
        
        {% block css %}{% endblock %} 

        {% block head %}
        <title>Elasstv - movie</title>
        {% endblock %}

    </head>


    <body id="page-top">

		{% block body %}
		
		{% include 'header-movie.html' %}

        <div id="sidebar-bg">
				  
				  <main id="col-main">
					  
					  <div class="dashboard-container">
						  
						  <ul class="dashboard-sub-menu">
							  <li class="current"><a href="dashboard-account.html">Account Settings</a></li>
						  </ul><!-- close .dashboard-sub-menu -->
						  
						  <div class="container-fluid">
							  <div class="row">
							  
								  <div class="col-12  col-lg-3">
									  <div id="account-edit-photo">
										  <div><img src="{% static 'accounts/images/profile-image-sidebar.jpg' %}" alt="Account Image"></div>
										  <p><a href="#!" class="btn btn-green-pro">Change Profile Picture</a></p>
										  <p><a href="#!" class="btn">Delete Photo</a></p>
									  </div>
								  </div><!-- close .col -->
								  <div class="col">
								  
									  <form class="account-settings-form">
								  
									  <h5>General Information</h5>
									  <p class="small-paragraph-spacing">By letting us know your name, we can make our support experience much more personal.</p>
									  <div class="row">
										  <div class="col-sm">
												<div class="form-group">
												  <label for="first-name" class="col-form-label">First Name:</label>
													<input type="text" class="form-control" id="first-name" value="{{ user.first_name}}">
												</div>
										  </div><!-- close .col -->
										  <div class="col-sm">
												   <div class="form-group">
													 <label for="last-name" class="col-form-label">Last Name:</label>
													   <input type="text" class="form-control" id="last-name" value="{{ user.last_name}}">
												   </div>
										  </div><!-- close .col -->
										  <div class="col-sm">
												   <div class="form-group">
												   </div>
										  </div><!-- close .col -->
									  </div><!-- close .row -->
									  <hr>
								  
									  <h5>Account Information</h5>
									  <p class="small-paragraph-spacing">You can change the email address you use here.</p>
									  
									  <div class="row">
										  <div class="col-sm">
												<div class="form-group">
												  <label for="e-mail" class="col-form-label">E-mail</label>
													<input type="text" class="form-control" id="e-mail" value="{{user.email}}">
												</div>
										  </div><!-- close .col -->
										  <div class="col-sm">
												   <div class="form-group">
													 <div><label for="button-change" class="col-form-label">&nbsp; &nbsp;</label></div>
													   <a href="#!" class="btn btn-form">Change E-mail</a>
												   </div>
										  </div><!-- close .col -->
										  
									  </div><!-- close .row -->
									  
									  <hr>
									  <h5>Change Password</h5>
									  <p class="small-paragraph-spacing">You can change the password you use for your account here.</p>
									  <div class="row">
										  <div class="col-sm">
												<div class="form-group">
												  <label for="password" class="col-form-label">Current Password:</label>
													<input type="text" class="form-control" id="password" value="&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;">
												</div>
										  </div><!-- close .col -->
										  <div class="col-sm">
												<div class="form-group">
												  <label for="new-password" class="col-form-label">New Password:</label>
													<input type="text" class="form-control" id="new-password" placeholder="Minimum of 6 characters">
												</div>
										  </div><!-- close .col -->
										  <div class="col-sm">
												<div class="form-group">
												  <div><label for="confirm-password" class="col-form-label">&nbsp; &nbsp;</label></div>
													<input type="text" class="form-control" id="confirm-password" placeholder="Confirm New Password">
												</div>
										  </div><!-- close .col -->
									  </div><!-- close .row -->
									  
										  <div class="clearfix"></div>
									  <hr>
									  <p><a href="#!" class="btn btn-green-pro">Save Changes</a></p>
									  <br>
									  </form>
								  
								  </div><!-- close .col -->
							  
							  </div><!-- close .row -->
						  </div><!-- close .container-fluid -->
								  
					  </div><!-- close .dashboard-container -->
				  </main>
				  
				  
				  </div><!-- close #sidebar-bg-->
				  
    	{% endblock %}

        {% block pre-footer %}
    
    	{% endblock %}

        {% include 'footer.html' %}

    </body>


</html>