Elsasstv/Elsasstv/urls.py
from django.contrib import admin
from django.urls import path, include


import Elsasstv.views as views

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('', include('django.contrib.auth.urls')),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('search/', include('search.urls')),
        
]

Elsasstv/movies/urls.py
from django.contrib import admin
from django.urls import path

import movies.views as views


app_name = 'movies'

urlpatterns = [

    path('', views.home, name='home'),
	path('<int:movie_id>/detail', views.detail, name="detail"),
    path('<int:person_id>/person-detail', views.person, name="person"),
    path('<int:movie_id>/create_favorite', views.create_favorite, name='create_favorite'),
    path('<int:movie_id>/remove_favorite', views.remove_favorite, name='remove_favorite'),
    
]

Elsasstv/movies/models.py
from django.db import models 
from django.contrib.auth.models import User


class Movie(models.Model):
    id = models.IntegerField(primary_key=True)
    imdb_id = models.CharField(max_length=45, null=True)
    original_title = models.CharField(max_length=200)
    title = models.CharField(max_length=200)  
    tagline = models.TextField()  
    overview = models.TextField()
    release_date = models.CharField(max_length=200, null=True)
    status = models.CharField(max_length=45)
    runtime = models.IntegerField(null=True)
    popularity = models.FloatField(null=True)
    original_language = models.CharField(max_length=200)
    poster_path = models.CharField(max_length=200, null=True)
    backdrop_path = models.CharField(max_length=200, null=True)    
    budget = models.BigIntegerField(null=True)
    revenue = models.BigIntegerField(null=True)   
    vote_average = models.FloatField(null=True)
    vote_count = models.IntegerField(null=True)

    users = models.ManyToManyField(User) #Relationship used to add movies in a user 'favorites'
    
    
class Person(models.Model):  
    id = models.IntegerField(primary_key=True)
    imdb_id = models.CharField(max_length=45)
    name = models.CharField(max_length=200)
    gender = models.IntegerField()
    birthday = models.DateTimeField(null=True)
    deathday = models.DateTimeField(null=True)
    place_of_birth = models.CharField(max_length=200,null=True)
    known_for_department = models.CharField(max_length=45,null=True)
    biography = models.TextField(null=True) 
    popularity = models.FloatField(null=True) 
    profile_path = models.CharField(max_length=200,null=True)
 

    

Elsasstv/movies/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User

from movies.models import Movie, Person
from movies.APIClient import APIClient
from accounts.get_friends import get_notif


def home(request):
    """View rendering the 100th more popular movies"""
    popular_movies = Movie.objects.order_by('-popularity')[:100]
    # Getting the requests for the notifications
    if request.user.is_authenticated:
        friend_requests = get_notif(request.user)
        nb_requests = len(friend_requests)
    return render(request, 'movies/home.html', locals())

def detail(request, movie_id):
    """View rendering the detailed informations of a movie""" 
    movie = get_object_or_404(Movie, pk=movie_id)
    person, director = APIClient().get_movie_credits(movie_id)
    similar_movies = APIClient().get_similar_movies(movie_id)
    # Getting the requests for the notifications
    if request.user.is_authenticated:
        friend_requests = get_notif(request.user)
        nb_requests = len(friend_requests)
    return render (request, 'movies/movie-detail.html', locals())

def person(request, person_id):
    """View rendering the detailed informations of a person""" 
    person = get_object_or_404(Person, pk=person_id)
    known_for_ids = APIClient().get_person_credits(person_id)
    known_for=[]
    try: 
        for id in known_for_ids:
            known_for.append(Movie.objects.get(pk=id))
    except:
        pass
    # Getting the requests for the notifications
    if request.user.is_authenticated:
        friend_requests = get_notif(request.user) 
        nb_requests = len(friend_requests)        
    return render(request, 'movies/person-detail.html', locals())

def create_favorite(request, movie_id):
    """Allows the user to add a favorite"""
    movie = Movie.objects.get(pk=movie_id)
    current_user = request.user
    movie.users.add(current_user)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def remove_favorite(request, movie_id):
    """Allows the user to remove a favorite"""
    movie = Movie.objects.get(pk=movie_id)
    user = request.user 
    movie.users.remove(user)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

Elsasstv/movies/templates/movies/home.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>

<html lang="en">

    <head>
        
        {% block css %}{% endblock %} 

        {% block head %}
        <title>Elasstv - movie</title>
        {% endblock %}

    </head>


    <body id="page-top">

		{% block body %}
		
		{% include 'header-movie.html' %}

        <div id="sidebar-bg">
				
				<main id="col-main">
						
					<div class="flexslider progression-studios-dashboard-slider progression-studios-full-height-slider">
							<ul class="slides">
							<li class="progression_studios_animate_left">
								<div class="progression-studios-slider-dashboard-image-background" style="background-image:url({% static 'movies/images/plans-background.jpg' %});">
									<div class="progression-studios-slider-display-table">
										<div class="progression-studios-slider-vertical-align">
										
											<div class="container">
												
												<a class="progression-studios-slider-play-btn afterglow" href="/movies/{{popular_movies.0.id}}/detail"><img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2/{{popular_movies.0.poster_path}}" alt="Listing"></a>
												
													<div
														class="circle-rating-pro"
														data-value="0.86"
														data-animation-start-value="0.86"
														data-size="70"
														data-thickness="6"
														data-fill="{
															&quot;color&quot;: &quot;#2325c2  &quot;
														}"
														data-empty-fill="#def6de"
														data-reverse="true"
													><span style="color:#2325c2  ;">{{popular_movies.0.vote_average}}</span></div>
											
												<div class="progression-studios-slider-dashboard-caption-width">
													<div class="progression-studios-slider-caption-align">
														<h6>Movies</h6>
														<ul class="progression-studios-slider-rating">
															<li>HD</li>
														</ul>
														<h2><a href="/movies/{{popular_movies.0.id}}/detail">{{popular_movies.0.title}}</a></h2>
														<ul class="progression-studios-slider-meta">
															<li>{{popular_movies.0.release_date}}</li>
															<li>{{popular_movies.0.runtime}} min.</li>
														</ul>
														<p class="progression-studios-slider-description">{{popular_movies.0.overview}}</p>
														
														
														<div class="clearfix"></div>      
											
														
													</div>  
												</div>  
											
											</div>  
										
										</div>  
									</div>  
								
									<div class="progression-studios-slider-mobile-background-cover"></div>
								</div>  
							</li>
					</div>  

					<div class="clearfix"></div>
					
					<div class="dashboard-container">

						<br>
						<h4 class="heading-extra-margin-bottom">Popular Movies</h4>
						<div class="row">
							{% for mov in popular_movies%}
                				<div class="col-12 col-md-6 col-lg-4 col-xl-3">
                				    <div class="item-listing-container-skrn">
                				        <a href="/movies/{{mov.id}}/detail"><img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2/{{mov.poster_path}}" alt="Listing"></a>
                				        <div class="item-listing-text-skrn">
                				            <div class="item-listing-text-skrn-vertical-align"><h6><a href="/movies/{{mov.id}}/detail">{{mov.title}}</a></h6>
                				              <div
                				                class="circle-rating-pro"
                				                data-value="0.86"
                				                data-animation-start-value="0.86"
                				                data-size="32"
                				                data-thickness="3"
                				                data-fill="{
                				                  &quot;color&quot;: &quot;#2325c2  &quot;
                				                }"
                				                data-empty-fill="#def6de"
                				                data-reverse="true"
                				              ><span style="color:#2325c2  ;">{{mov.vote_average}}</span></div>
                				            </div>  
                				        </div>  
                				    </div>  
                				</div>  
							{% endfor %} 
							<ul>
						</div>  
						
					</div>  
				</main>
				
				
				</div>  
    	{% endblock %}

        {% block pre-footer %}
    
    	{% endblock %}

        {% include 'footer.html' %}

    </body>


</html>

Elsasstv/movies/templates/movies/movie-detail.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>

<html lang="en">

    <head>
        
        {% block css %}{% endblock %} 

        {% block head %}
        <title>Elasstv - movie</title>
        {% endblock %}

    </head>


    <body id="page-top">

		{% block body %}
		
		{% include 'header-movie.html' %}


        <div id="sidebar-bg">
						
			<div id="content-sidebar-pro">
			
				<div id="content-sidebar-image">
					<img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2/{{movie.poster_path}}" alt="Movie Poster">
				</div>
				
				<div class="content-sidebar-section">
					<h2 class="content-sidebar-sub-header">{{movie.title}}</h2>
					<ul class="progression-studios-slider-rating">
						<li>HD</li>
					</ul>
				</div>  
				
				<div class="content-sidebar-section">
					<h4 class="content-sidebar-sub-header">Release Date</h4>
					<div class="content-sidebar-short-description">{{movie.release_date}}</div>
				</div>  
				
				<div class="content-sidebar-section">
					<h4 class="content-sidebar-sub-header">Length</h4>
					<div class="content-sidebar-short-description">{{movie.runtime}} min</div>
				</div>  
				
				<div class="content-sidebar-section">
					<h4 class="content-sidebar-sub-header">Director</h4>
					<div class="content-sidebar-short-description"><a href='/movies/{{director.id}}/person-detail'>{{ director.name }}</a></div>
				</div>  
	
				
				
				<div class="content-sidebar-section">
					<h2 class="content-sidebar-sub-header adjusted-recent-reviews">Recent Reviews</h2>
					<ul id="sidebar-reviews-pro">
						<li>
						  <div
							class="circle-rating-pro"
							data-value="0.86"
							data-animation-start-value="0.86"
							data-size="32"
							data-thickness="3"
							data-fill="{
							  &quot;color&quot;: &quot;#2325c2  &quot;
							}"
							data-empty-fill="#def6de"
							data-reverse="true"
						  ><span style="color:#2325c2  ;">8.6</span></div>
							<h6>Dan Cederholm</h6>
							<div class="sidebar-review-time">October 22, 2017</div>
							<div class="spoiler-review">Contains Spoiler</div>
							<p>They don't make many Sci-Fi films these days. This was a pleasant surprise all throughout the film. I really like this film.</p>
						</li>
					</ul>
				</div>  
				
			</div>  
			
			<main id="col-main-with-sidebar">
				
				<div id="movie-detail-header-pro" style="background-image:url('https://image.tmdb.org/t/p/w1400_and_h450_face/{{movie.backdrop_path}}')">
					
					{% if user.is_authenticated %}
					<div class="progression-studios-slider-more-options">
						<i class="fas fa-heart"></i>
						<ul>
							<li><a href="{% url 'movies:create_favorite' movie.id %}">Add to Fav</a></li>
							<li><a href="{% url 'movies:remove_favorite' movie.id %}">Remove Fav</a></li>
							
						</ul>
					</div>
					{% endif %}
					
					
					
					<div id="movie-detail-header-media">
					</div>  
					
					<div id="movie-detail-gradient-pro"></div>
				</div>  
				
				
				<div id="movie-detail-rating">
					<div class="dashboard-container-movie">
						<div class="row">
							<div class="col-sm">
								<h5>{{movie.title}}</h5>
								
								<div class="rating-pro">
									 <label>
									   <input type="radio" name="rating-pro" value="10" title="10 stars"> 10
									 </label>
									<label>
									  <input type="radio" name="rating-pro" value="9" title="9 stars"> 9
									</label>
									<label>
									  <input type="radio" name="rating-pro" value="8" title="8 stars"> 8
									</label>
									<label>
									  <input type="radio" name="rating-pro" value="7" title="7 stars"> 7
									</label>
								   <label>
									 <input type="radio" name="rating-pro" value="6" title="6 stars"> 6
								   </label>
								  <label>
									<input type="radio" name="rating-pro" value="5" title="5 stars"> 5
								  </label>
								  <label>
									<input type="radio" name="rating-pro" value="4" title="4 stars"> 4
								  </label>
								  <label>
									<input type="radio" name="rating-pro" value="3" title="3 stars"> 3
								  </label>
								  <label>
									<input type="radio" name="rating-pro" value="2" title="2 stars"> 2
								  </label>
								  <label>
									<input type="radio" name="rating-pro" value="1" title="1 star"> 1
								  </label>
								</div>
								
							</div>
							<div class="col-sm">
								<h6>Vote average</h6>
							  <div
								class="circle-rating-pro"
								data-value="0.86"
								data-animation-start-value="0.86"
								data-size="40"
								data-thickness="3"
								data-fill="{
								  &quot;color&quot;: &quot;#2325c2  &quot;
								}"
								data-empty-fill="#def6de"
								data-reverse="true"
							  ><span style="color:#2325c2  ;">{{movie.vote_average}}</span></div>
								<div class="clearfix"></div>
							</div>
						</div>  
					</div>  
				</div>  
				
				<div class="dashboard-container">
					
					
					<div class="movie-details-section">
						<h2>Overview</h2>
						<p>{{movie.overview}}</p>
					</div>  
	
					<div class="movie-details-section">
						<h2>The Cast</h2>
						<div class="row">

								{% for pers in person|slice:":8"%}
									<div class="col-12 col-md-6 col-lg-6 col-xl-4">
										<div class="item-listing-container-skrn">
											<a href="/movies/{{pers.id}}/person-detail"><img src="{{pers.profile_path}}" alt="Cast"></a>
											<div class="item-listing-text-skrn item-listing-movie-casting">
												<h6><a href="/movies/{{pers.id}}/person-detail">{{pers.name}}</a></h6>
												<div class="movie-casting-sub-title">{{pers.know_for_department}}</div>
											</div>  
										</div>  
									</div>  
								{% endfor %} 
						</div>  
					</div>  
	
						
					<div class="movie-details-section">
						<h2>Similar Movies</h2>
						<div class="row">

								{% for movie in similar_movies|slice:":8" %}
                				<div class="col-12 col-md-6 col-lg-4 col-xl-3">
                				    <div class="item-listing-container-skrn">
                				        <a href="/movies/{{movie.id}}/detail"><img src="{{movie.poster_path}}" alt="Listing"></a>
                				        <div class="item-listing-text-skrn">
                				            <div class="item-listing-text-skrn-vertical-align"><h6><a href="/movies/{{movie.id}}/detail">{{movie.title}}</a></h6>
                				              <div
                				                class="circle-rating-pro"
                				                data-value="0.86"
                				                data-animation-start-value="0.86"
                				                data-size="32"
                				                data-thickness="3"
                				                data-fill="{
                				                  &quot;color&quot;: &quot;#2325c2  &quot;
                				                }"
                				                data-empty-fill="#def6de"
                				                data-reverse="true"
                				              ><span style="color:#2325c2  ;">{{movie.vote_average}}</span></div>
                				            </div>  
                				        </div>  
                				    </div>  
                				</div>  
							{% endfor %} 
						
						
						</div>  
					
					</div>  
					
				</div>  
			</main>
			
					
				</div>  
    	{% endblock %}

        {% block pre-footer %}
    
    	{% endblock %}

        {% include 'footer.html' %}

    </body>


</html>

Elsasstv/movies/templates/movies/person-detail.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>

<html lang="en">

    <head>
        
        {% block css %}{% endblock %} 

        {% block head %}
        <title>Elasstv - movie</title>
        {% endblock %}

    </head>


    <body id="page-top">

		{% block body %}
		
		{% include 'header-movie.html' %}

        <div id="sidebar-bg">
				
			<div id="content-sidebar-pro">
			
				<div id="content-sidebar-image">
					<img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2/{{person.profile_path}}" alt="Movie Poster">
				</div>
				
				<div class="content-sidebar-section">
					<h2 class="content-sidebar-sub-header">{{person.name}}</h2>
					<ul class="progression-studios-slider-rating">
					</ul>
				</div>  
				
				<div class="content-sidebar-section">
					<h4 class="content-sidebar-sub-header">Gender:</h4>
					<div class="content-sidebar-short-description">{{person.gender}}</div>
				</div>  
				
				<div class="content-sidebar-section">
					<h4 class="content-sidebar-sub-header">Place of birth:</h4>
					<div class="content-sidebar-short-description">{{person.place_of_birth}}</div>
				</div>  
				
				<div class="content-sidebar-section">
					<h4 class="content-sidebar-sub-header">known for:</h4>
					<div class="content-sidebar-short-description">{{person.known_for_department}}</div>
				</div>  
	
				
				
				<div class="content-sidebar-section">
					<h2 class="content-sidebar-sub-header adjusted-recent-reviews">Recent Reviews</h2>
					<ul id="sidebar-reviews-pro">
						<li>
						  <div
							class="circle-rating-pro"
							data-value="0.86"
							data-animation-start-value="0.86"
							data-size="32"
							data-thickness="3"
							data-fill="{
							  &quot;color&quot;: &quot;#2325c2  &quot;
							}"
							data-empty-fill="#def6de"
							data-reverse="true"
						  ><span style="color:#2325c2  ;">8.6</span></div>
							<h6>Dan Cederholm</h6>
							<div class="sidebar-review-time">October 22, 2017</div>
							<div class="spoiler-review">Contains Spoiler</div>
							<p>They don't make many Sci-Fi films these days. This was a pleasant surprise all throughout the film. I really like this film.</p>
						</li>
					</ul>
				</div>  
				
			</div>  
			
			
			<main id="col-main-with-sidebar">
				
				<div id="person-detail-header-pro" >
					
						<div id="person-detail-gradient-pro">

								<div class="content-sidebar-section">
										<h1 class="content-sidebar-sub-header">{{person.name}}</h1>
									</div>  

									<div class="content-sidebar-section">
											<h1 class="content-sidebar-sub-header">Biography</h1><br>
											<div class="content-sidebar-short-description">{{person.biography}}</div>
										</div>  


										<br><br>
						</div>
				</div>  
				
				
				<div class="dashboard-container">
					
					
					<div class="movie-details-section"><br><br>
						<h2>Known for</h2>
						<div class="row">

								{% for movie in known_for|slice:":8" %}
                				<div class="col-12 col-md-6 col-lg-4 col-xl-3">
                				    <div class="item-listing-container-skrn">
                				        <a href="/movies/{{movie.id}}/detail"><img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2/{{movie.poster_path}}" alt="Listing"></a>
                				        <div class="item-listing-text-skrn">
                				            <div class="item-listing-text-skrn-vertical-align"><h6><a href="/movies/{{movie.id}}/detail">{{movie.title}}</a></h6>
                				              <div
                				                class="circle-rating-pro"
                				                data-value="0.86"
                				                data-animation-start-value="0.86"
                				                data-size="32"
                				                data-thickness="3"
                				                data-fill="{
                				                  &quot;color&quot;: &quot;#2325c2  &quot;
                				                }"
                				                data-empty-fill="#def6de"
                				                data-reverse="true"
                				              ><span style="color:#2325c2  ;">{{movie.vote_average}}</span></div>
                				            </div>  
                				        </div>  
                				    </div>  
                				</div>  
							{% endfor %} 
						</div>  
					</div>  
	
					<div class="movie-details-section">
						
					</div>  
	
						
					<div class="movie-details-section">
					
					</div>  
					
				</div>  
			</main>
			
					
				</div>  
    	{% endblock %}

        {% block pre-footer %}
    
    	{% endblock %}

        {% include 'footer.html' %}

    </body>

</html>