Elsasstv/Elsasstv/urls.py
from django.contrib import admin
from django.urls import path, include


import Elsasstv.views as views

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('', include('django.contrib.auth.urls')),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('search/', include('search.urls')),
        
]

Elsasstv/accounts/urls.py
from django.contrib import admin
from django.urls import path


import accounts.views as views


app_name = 'accounts'

urlpatterns = [

    path('profile', views.profile, name='profile'),
    path('settings', views.settings, name='settings'),
    path('list_users', views.list_users, name='list_users'),
    path('<int:friend_id>/friend_request', views.friend_request, name='friend_request'),
    path('<int:friendship_id>/<int:status>/accept_or_refuse', views.accept_or_refuse, name='accept_or_refuse'),
    path('<int:friend_id>/delete_friend', views.delete_friend, name='delete_friend'),
    path('<int:friend_id>/friend_infos', views.friend_infos, name='friend_infos'),
    

]

Elsasstv/movies/urls.py
from django.contrib import admin
from django.urls import path

import movies.views as views


app_name = 'movies'

urlpatterns = [

    path('', views.home, name='home'),
	path('<int:movie_id>/detail', views.detail, name="detail"),
    path('<int:person_id>/person-detail', views.person, name="person"),
    path('<int:movie_id>/create_favorite', views.create_favorite, name='create_favorite'),
    path('<int:movie_id>/remove_favorite', views.remove_favorite, name='remove_favorite'),
    
]

Elsasstv/Elsasstv/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    """This class, herited from UserCreationForm, allows for the creation of form objects used to register
    a new user.
    """
    username = forms.CharField(max_length=30, help_text='Required')
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    email = forms.EmailField(max_length=254, required=False, help_text='Optional')

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2', 
        )
        

class UserForm(forms.Form):
    """Class used for the authentification of users"""
    username = forms.CharField(max_length=40)
    password = forms.CharField(max_length=20, widget=forms.PasswordInput)

Elsasstv/templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

    <head>

            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
            <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Lato:400,700%7CMontserrat:300,400,600,700">
            <link rel="stylesheet" href="{% static 'icons/fontawesome/css/fontawesome-all.min.css' %}">  
            <link rel="stylesheet" href="{% static 'icons/Iconsmind__Ultimate_Pack/Line%20icons/styles.min.css' %}">  
            
            <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>       
    

        {% block css %}{% endblock %} 
        {% block head %}
        <title>Elsasstv</title>
        {% endblock %}

    </head>


    <body id="page-top">        

        {% block body %}

        {% include 'header.html' %}
        {% include 'login.html' %}

    	{% endblock %}

        {% block pre-footer %}
    
    	{% endblock %}

        {% include 'footer.html' %}

    </body>

</html>

Elsasstv/templates/footer.html
{% load static %}

<footer id="footer-pro">
  <div class="container">
    <div class="row">
      <div class="col-md">
        <div class="copyright-text-pro">&copy; Copyright 2019 Elsasstv. Made with love by AF students</div>
      </div>  
      <div class="col-md">
        <ul class="social-icons-pro">
          <li class="facebook-color"><a href="" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
          <li class="twitter-color"><a href="" target="_blank"><i class="fab fa-twitter"></i></a></li>
          <li class="youtube-color"><a href="" target="_blank"><i class="fab fa-youtube"></i></a></li>
          <li class="vimeo-color"><a href="" target="_blank"><i class="fab fa-vimeo-v"></i></a></li>
        </ul>
      </div>  
    </div>  
  </div>  
</footer>

<a href="#0" id="pro-scroll-top"><i class="fas fa-chevron-up"></i></a>

  
<script src="{% static 'js/libs/jquery-3.3.1.min.js' %}"></script>  
<script src="{% static 'js/libs/popper.min.js' %}" ></script>  
<script src="{% static 'js/libs/bootstrap.min.js' %}" ></script>    

  
<script src="{% static 'js/navigation.js' %}" ></script>  
<script src="{% static 'js/jquery.flexslider-min.js' %}" ></script>  		
<script src="{% static 'js/script.js' %}" ></script>
<script src="{% static 'js/jquery-asRange.min.js' %}" defer></script>
<script src="{% static 'js/circle-progress.min.js' %}" defer></script>
<script src="{% static 'js/afterglow.min.js' %}" defer></script>
<script src="{% static 'js/script-dashboard.js' %}" defer></script>
{% if new_user.errors %} <script src="{% static 'js/LoginModal.js' %}" ></script> {% endif %}
{% if login_user.errors %} <script src="{% static 'js/RegisterModal.js' %}" ></script> {% endif %}

Elsasstv/templates/header-movie.html
{% load static %}

<header id="videohead-pro" class="sticky-header">
    <div id="video-logo-background"><a href="/"><img src="{% static 'images/logo.png' %}" alt="Logo"></a></div>
    
    <div id="video-search-header">

        <form action="/search/" method="get">
        <input id='q'  name='q' type="text" placeholder="Search for Movies or TV Series" aria-label="Search">
        </form>
        
        <div id="video-search-header-filtering">
        </div>  
    </div>  
    
    
    {% if user.is_authenticated %}

    <div id="header-user-profile">
        <div id="header-user-profile-click" class="noselect">
                 <div id="header-username">Hi, {{user.username}}</div><i class="fas fa-angle-down"></i>
        </div>  
        <div id="header-user-profile-menu">
            <ul>
                <li><a href="/accounts/profile"><span class="icon-User"></span>My Profile</a></li>
                <li><a href="/accounts/profile"><span class="icon-Favorite-Window"></span>My Favorites</a></li>
                <li><a href="/accounts/settings"><span class="icon-Gears"></span>Account Details</a></li>
                <li><a href="/logout"><span class="icon-Power-3"></span>Log Out</a></li>
            </ul>
        </div>  
    </div> 
    
    
    <div id="header-user-notification">
        <div id="header-user-notification-click" class="noselect">
            <i class="far fa-bell"></i>
            <span class="user-notification-count">{{ nb_requests }}</span>
        </div>  
        <div id="header-user-notification-menu">
            <h3>Notifications</h3>
            <div id="header-notification-menu-padding">
                <ul id="header-user-notification-list">
                    {% for friendship in friend_requests %}
                    <li>
                        
                        <a>
                        <img src="{% static 'images/user-profile-2.jpg' %}" alt="Profile">
                        <strong>{{ friendship.source_user.user.username }}</strong> wants to be your friend  </a>

                        <div class="notify-button row">
                            <div class="notif col-xs-6">
                            <a href="{% url 'accounts:accept_or_refuse' friendship.id 1 %}" class="btn btn-accept button-notif">Accept</a> </div>
                            <div class="notif col-xs-6">
                             <a href="{% url 'accounts:accept_or_refuse' friendship.id 2 %}" class="btn btn-refuse button-notif">Refuse</a></div>
                            </div>
                    </li>
                    {% endfor %}</ul>
                <div class="clearfix"></div>
            </div>
            </div>
            
    </div>
      
    {% endif %} 
    
    
    <div class="clearfix"></div>
    
    <nav id="sidebar-nav">  
        <ul id="vertical-sidebar-nav" class="sf-menu">
            <li class="normal-item-pro current-menu-item">
                <a href="/movies">
        <span class="icon-Reel"></span>
                    Movies
                </a>
            </li>
            
            <li class="normal-item-pro">
                <a href="#">
        <span class="icon-Old-TV"></span>
                    TV Show
                </a>
            </li>
            <li class="normal-item-pro">
                <a href="#">
        <span class="icon-Movie-Ticket"></span>
                    New Arrivals
                </a>
            </li>
            <li class="normal-item-pro">
                <a href="#">
        <span class="icon-Clock"></span>
                    Coming Soon
                </a>
            </li>

        </ul>
<div class="clearfix"></div>
</nav>

    
    </header>

Elsasstv/templates/header.html
{% load static %}

<header id="masthead-pro">
  <div class="container">
    
    <h1><a href=""><img src="{% static 'images/logo.png' %}" alt="Logo"></a></h1>
    
    <nav id="site-navigation-pro">
      <ul class="sf-menu">
        <li class="normal-item-pro current-menu-item">
          <a href="">Home</a>
        </li>
        <li class="normal-item-pro">
          <a href="/movies">Movies</a>
        </li>
        <li class="normal-item-pro">
          <a href="movies">TV show (coming soon)</a>
        </li>
        
      </ul>
    </nav>
    
     {% if user.is_authenticated %} 
      <a href="/logout"><button class="btn btn-header-pro" role="button">Sign out</button></a>
     {% else %} 
      <button class="btn btn-header-pro noselect" data-toggle="modal" data-target="#LoginModal" role="button">Sign In</button>  
     {% endif %} 
    
    <div class="clearfix"></div>
  </div>  
  
</header>

Elsasstv/templates/home.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>

<html lang="en">

    <head>
        
        {% block css %}{% endblock %} 

        {% block head %}
        <title>Elasstv</title>
        {% endblock %}

    </head>


    <body id="page-top">        

        {% block body %}
        {% include 'header.html' %}
        {% include 'login.html' %}
        {% include 'register.html' %}

        <div class="flexslider progression-studios-slider">
            <ul class="slides">
                  <li class="progression_studios_animate_in">
                      <div class="progression-studios-slider-image-background" style="background-image:url({% static 'images/slide-1.jpg' %});">
                          <div class="progression-studios-slider-display-table">
                              <div class="progression-studios-slider-vertical-align">
                                  
                                  <div class="container">
                                      
                                      <div class="progression-studios-slider-caption-width">
                                          <div class="progression-studios-slider-caption-align">
                                              <h2>Welcome to Elsasstv<span style="color:#2325c2  ;">.</span></h2>
                                              <h6>Watch the largest collection of Movies and TV series anytime anywhere!</h6>
                                              <a class="btn btn-green-pro btn-slider-pro btn-shadow-pro" href="/movies" role="button">Start now !</a>
                                          </div>  
                                      </div>  
                                      
                                  </div>  
                                  
                              </div>  
                          </div>  
                          
                      </div>  
                  </li>
              </ul>
          </div>
          



          <div class="dashboard-container">
				
            <h4 class="heading-extra-margin-bottom">Most Popular TV-Show</h4>
            <div class="row">

                    {% for movie in popular_movies%}
                <div class="col-12 col-md-6 col-lg-4 col-xl-3">
                    <div class="item-listing-container-skrn">
                        <a href="/movies/{{movie.id}}/detail"><img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2/{{movie.poster_path}}" alt="Listing"></a>
                        <div class="item-listing-text-skrn">
                            <div class="item-listing-text-skrn-vertical-align"><h6><a href="/movies/{{movie.id}}/detail">{{movie.title}}</a></h6>
                              <div
                                class="circle-rating-pro"
                                data-value="1"
                                data-animation-start-value="0"
                                data-size="32"
                                data-thickness="3"
                                data-fill="{
                                  &quot;color&quot;: &quot;#2325c2  &quot;
                                }"
                                data-empty-fill="#def6de"
                                data-reverse="true"
                              ><span style="color:#2325c2  ;">{{movie.vote_average}}</span></div>
                            </div>  
                        </div>  
                    </div>  
                </div>  
                {% endfor %}

            </div>  
                               
        </div>  
       

    	{% endblock %}

        {% block pre-footer %}
    
    	{% endblock %}

        {% include 'footer.html' %}

        
    </body>


</html>

Elsasstv/templates/login.html
{% load static %}

  
<div class="modal fade" id="LoginModal" tabindex="-1" role="dialog" aria-labelledby="LoginModal" aria-hidden="true">
    <button type="button" class="close float-close-pro" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
   </button>
 <div class="modal-dialog modal-dialog-centered modal-md" role="document">
   <div class="modal-content">
        <div class="modal-header-pro">
            <h2>Welcome Back</h2>
            <h6>Sign in to your account to continue using Elsasstv</h6>
        </div>
        <div class="modal-body-pro social-login-modal-body-pro">
            
            
                <form method="POST">
                   <!--  <div class="form-group">
                        <input type="text" class="form-control" id="username" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" id="password" placeholder="Password">
                    </div> -->
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class ="form-control" name="username" maxlength="40" required="" id="id_username" placeholder="username">
                    </div>
                    <div class="form-group">
                        <input type="password" class ="form-control" name="password" maxlength="20" required="" id="id_password" placeholder="password">
                    </div>
                    
                    <div class="form-group">
                        <button type="submit" class="btn btn-green-pro btn-display-block">Sign In</button>
                    </div>
                    <div class="container-fluid">
                        <div class="row no-gutters">
                            {% comment %} <div class="col checkbox-remember-pro"><input type="checkbox" id="checkbox-remember"><label for="checkbox-remember" class="col-form-label">Remember me</label></div> {% endcomment %}
                           <div class="col forgot-your-password"><a href="{% url 'password_reset' %}">Forgot your password?</a></div>
                       </div>
                   </div>  
       
                </form>
      </div>  

        <button class="btn btn-header-pro noselect" data-toggle="modal" data-target="#RegisterModal" role="button">Register</button>   
   </div>  
 </div>  
</div>  

Elsasstv/templates/register.html
{% load static %}

  
<div class="modal fade" id="RegisterModal" tabindex="-1" role="dialog" aria-labelledby="RegisterModal" aria-hidden="true">
    <button type="button" class="close float-close-pro" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
   </button>
  <div class="modal-dialog modal-dialog-centered modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header-pro">
          <h2>Registration</h2>
          <h6>Create an account for Elsasstv</h6>
      </div>
      <div class="modal-body-pro social-login-modal-body-pro">    
          <form class = 'form-group' method="post">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" class ="form-control" name="username" maxlength="30" autofocus="" required="" id="id_username" placeholder="username"> 
            </div>
            <div class="form-group">
                <input type="text" class ="form-control" name="first_name" maxlength="30" id="id_first_name" placeholder="first name (optionnal)">
            </div>
            <div class="form-group">
                <input type="text" class ="form-control" name="last_name" maxlength="30" id="id_last_name" placeholder="last name (optionnal)">
            </div>
            <div class="form-group">
                <input type="email" class ="form-control" name="email" maxlength="254" id="id_email" placeholder="email (optionnal)">
            </div>
            <div class="form-group">
                <input type="password" class ="form-control" name="password1" required="" id="id_password1" placeholder="password"> 
            </div>
            <div class="form-group">
                <input type="password" class ="form-control" name="password2" required="" id="id_password2" placeholder="repeat password"> 
            </div>
            
            <button type="submit" class="btn btn-green-pro btn-display-block">Register</button>
          </form>
      </div> 
    </div>  
  </div>  
</div>  
 